name: Translations
on: [pull_request]

jobs:
  test:
    name: Pushing translations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'bun'
      - name: Install deps (Translations)
        run: bun install --frozen-lockfile
      - name: Generate translations
        working-directory: .
        env:
          LOCALAZY_WRITE_KEY: ${{ secrets.LOCALAZY_WRITE_KEY }}
          LOCALAZY_READ_KEY: ${{ secrets.LOCALAZY_READ_KEY }}
        run: bun translations:generate && bun translations:push
