name: Tests - Web, UI
on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'bun'
      - name: Install deps (Translations)
        working-directory: .
        run: bun install --frozen-lockfile
      - name: Generate translations
        working-directory: .
        run: |
          bun translations:generate
          bun translations:generate-index
      - name: Install deps
        run: bun install --frozen-lockfile
      - name: Linting
        run: bun lint
      - name: Type checking
        run: bun tsc
